=== Mathew-Westfields/Academic-Projects/XML-Project/Corona.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="day_data">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="positiv_getestet" type="xs:integer"/>
      <xs:element name="geschaetzt_infektioes" type="xs:integer"/>
      <xs:element name="inzidenz" type="xs:decimal"/>
      <xs:element name="genesen" type="xs:integer"/>
    </xs:sequence> 
    <xs:attribute name="date" type="xs:date" use="required"/>
  </xs:complexType>
</xs:element>

<xs:element name="month_data">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="day_data" minOccurs="1" maxOccurs="31"/>
        </xs:sequence>
        <xs:attribute name = "first_date" type="xs:date"/>
        <xs:attribute name = "last_date" type="xs:date"/>
    </xs:complexType>
</xs:element>

<xs:element name="corona_data">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="month_data" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>

</xs:schema>

=== Mathew-Westfields/Academic-Projects/XML-Project/parsed_corona_data.xml
<?xml version="1.0" encoding="UTF-8"?>
<corona_data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="Corona.xsd">
    <month_data first_date = "2021-08-02" last_date="2021-08-31">
        <day_data date="2021-08-31">
        <positiv_getestet>14</positiv_getestet>
        <geschaetzt_infektioes>1200</geschaetzt_infektioes>
        <inzidenz>161</inzidenz>
        <genesen>16000</genesen>
    </day_data>
<day_data date="2021-08-30">
        <positiv_getestet>39</positiv_getestet>
        <geschaetzt_infektioes>1300</geschaetzt_infektioes>
        <inzidenz>169.7</inzidenz>
        <genesen>16000</genesen>
    </day_data>
<day_data date="2021-08-27">
        <positiv_getestet>86</positiv_getestet>
        <geschaetzt_infektioes>1100</geschaetzt_infektioes>
        <inzidenz>165.5</inzidenz>
        <genesen>15900</genesen>
    </day_data>
<day_data date="2021-08-26">
        <positiv_getestet>134</positiv_getestet>
        <geschaetzt_infektioes>1100</geschaetzt_infektioes>
        <inzidenz>171.5</inzidenz>
        <genesen>15800</genesen>
    </day_data>
<day_data date="2021-08-25">
        <positiv_getestet>108</positiv_getestet>
        <geschaetzt_infektioes>1000</geschaetzt_infektioes>
        <inzidenz>159.5</inzidenz>
        <genesen>15800</genesen>
    </day_data>
<day_data date="2021-08-24">
        <positiv_getestet>54</positiv_getestet>
        <geschaetzt_infektioes>920</geschaetzt_infektioes>
        <inzidenz>160.7</inzidenz>
        <genesen>15700</genesen>
    </day_data>
<day_data date="2021-08-23">
        <positiv_getestet>77</positiv_getestet>
        <geschaetzt_infektioes>890</geschaetzt_infektioes>
        <inzidenz>161.9</inzidenz>
        <genesen>15700</genesen>
    </day_data>
<day_data date="2021-08-22">
        <positiv_getestet>70</positiv_getestet>
        <geschaetzt_infektioes>830</geschaetzt_infektioes>
        <inzidenz>146.9</inzidenz>
        <genesen>15700</genesen>
    </day_data>
<day_data date="2021-08-21">
        <positiv_getestet>81</positiv_getestet>
        <geschaetzt_infektioes>770</geschaetzt_infektioes>
        <inzidenz>140.9</inzidenz>
        <genesen>15700</genesen>
    </day_data>
<day_data date="2021-08-20">
        <positiv_getestet>125</positiv_getestet>
        <geschaetzt_infektioes>700</geschaetzt_infektioes>
        <inzidenz>130.5</inzidenz>
        <genesen>15700</genesen>
    </day_data>
<day_data date="2021-08-19">
        <positiv_getestet>95</positiv_getestet>
        <geschaetzt_infektioes>590</geschaetzt_infektioes>
        <inzidenz>103.8</inzidenz>
        <genesen>15700</genesen>
    </day_data>
<day_data date="2021-08-18">
        <positiv_getestet>107</positiv_getestet>
        <geschaetzt_infektioes>510</geschaetzt_infektioes>
        <inzidenz>91.3</inzidenz>
        <genesen>15600</genesen>
    </day_data>
<day_data date="2021-08-17">
        <positiv_getestet>24</positiv_getestet>
        <geschaetzt_infektioes>410</geschaetzt_infektioes>
        <inzidenz>73.3</inzidenz>
        <genesen>15600</genesen>
    </day_data>
<day_data date="2021-08-16">
        <positiv_getestet>16</positiv_getestet>
        <geschaetzt_infektioes>400</geschaetzt_infektioes>
        <inzidenz>71.2</inzidenz>
        <genesen>15600</genesen>
    </day_data>
<day_data date="2021-08-15">
        <positiv_getestet>45</positiv_getestet>
        <geschaetzt_infektioes>390</geschaetzt_infektioes>
        <inzidenz>68.5</inzidenz>
        <genesen>15600</genesen>
    </day_data>
<day_data date="2021-08-14">
        <positiv_getestet>48</positiv_getestet>
        <geschaetzt_infektioes>360</geschaetzt_infektioes>
        <inzidenz>58.6</inzidenz>
        <genesen>15600</genesen>
    </day_data>
<day_data date="2021-08-13">
        <positiv_getestet>40</positiv_getestet>
        <geschaetzt_infektioes>310</geschaetzt_infektioes>
        <inzidenz>50.6</inzidenz>
        <genesen>15600</genesen>
    </day_data>
<day_data date="2021-08-12">
        <positiv_getestet>56</positiv_getestet>
        <geschaetzt_infektioes>280</geschaetzt_infektioes>
        <inzidenz>44.9</inzidenz>
        <genesen>15600</genesen>
    </day_data>
<day_data date="2021-08-11">
        <positiv_getestet>35</positiv_getestet>
        <geschaetzt_infektioes>240</geschaetzt_infektioes>
        <inzidenz>32.0</inzidenz>
        <genesen>15600</genesen>
    </day_data>
<day_data date="2021-08-10">
        <positiv_getestet>10</positiv_getestet>
        <geschaetzt_infektioes>210</geschaetzt_infektioes>
        <inzidenz>30.2</inzidenz>
        <genesen>15600</genesen>
    </day_data>
<day_data date="2021-08-09">
        <positiv_getestet>5</positiv_getestet>
        <geschaetzt_infektioes>210</geschaetzt_infektioes>
        <inzidenz>29.3</inzidenz>
        <genesen>15600</genesen>
    </day_data>
<day_data date="2021-08-06">
        <positiv_getestet>13</positiv_getestet>
        <geschaetzt_infektioes>180</geschaetzt_infektioes>
        <inzidenz>29.0</inzidenz>
        <genesen>15600</genesen>
    </day_data>
<day_data date="2021-08-05">
        <positiv_getestet>26</positiv_getestet>
        <geschaetzt_infektioes>150</geschaetzt_infektioes>
        <inzidenz>30.2</inzidenz>
        <genesen>15600</genesen>
    </day_data>
<day_data date="2021-08-04">
        <positiv_getestet>17</positiv_getestet>
        <geschaetzt_infektioes>140</geschaetzt_infektioes>
        <inzidenz>26.6</inzidenz>
        <genesen>15600</genesen>
    </day_data>
<day_data date="2021-08-03">
        <positiv_getestet>12</positiv_getestet>
        <geschaetzt_infektioes>130</geschaetzt_infektioes>
        <inzidenz>26.6</inzidenz>
        <genesen>15500</genesen>
    </day_data>
<day_data date="2021-08-02">
        <positiv_getestet>0</positiv_getestet>
        <geschaetzt_infektioes>130</geschaetzt_infektioes>
        <inzidenz>26.9</inzidenz>
        <genesen>15500</genesen>
    </day_data>

        </month_data>
<month_data first_date = "2021-05-12" last_date="2021-05-31">
        <day_data date="2021-05-31">
        <positiv_getestet>6</positiv_getestet>
        <geschaetzt_infektioes>1500</geschaetzt_infektioes>
        <inzidenz>52.1</inzidenz>
        <genesen>13800</genesen>
    </day_data>
<day_data date="2021-05-30">
        <positiv_getestet>23</positiv_getestet>
        <geschaetzt_infektioes>1500</geschaetzt_infektioes>
        <inzidenz>51.8</inzidenz>
        <genesen>13700</genesen>
    </day_data>
<day_data date="2021-05-29">
        <positiv_getestet>46</positiv_getestet>
        <geschaetzt_infektioes>1500</geschaetzt_infektioes>
        <inzidenz>52.4</inzidenz>
        <genesen>13700</genesen>
    </day_data>
<day_data date="2021-05-28">
        <positiv_getestet>47</positiv_getestet>
        <geschaetzt_infektioes>1500</geschaetzt_infektioes>
        <inzidenz>62.8</inzidenz>
        <genesen>13700</genesen>
    </day_data>
<day_data date="2021-05-27">
        <positiv_getestet>52</positiv_getestet>
        <geschaetzt_infektioes>1600</geschaetzt_infektioes>
        <inzidenz>61.0</inzidenz>
        <genesen>13500</genesen>
    </day_data>
<day_data date="2021-05-26">
        <positiv_getestet>7</positiv_getestet>
        <geschaetzt_infektioes>1700</geschaetzt_infektioes>
        <inzidenz>60.1</inzidenz>
        <genesen>13500</genesen>
    </day_data>
<day_data date="2021-05-25">
        <positiv_getestet>4</positiv_getestet>
        <geschaetzt_infektioes>1800</geschaetzt_infektioes>
        <inzidenz>92.5</inzidenz>
        <genesen>13300</genesen>
    </day_data>
<day_data date="2021-05-24">
        <positiv_getestet>22</positiv_getestet>
        <geschaetzt_infektioes>1900</geschaetzt_infektioes>
        <inzidenz>107.4</inzidenz>
        <genesen>13200</genesen>
    </day_data>
<day_data date="2021-05-23">
        <positiv_getestet>40</positiv_getestet>
        <geschaetzt_infektioes>2000</geschaetzt_infektioes>
        <inzidenz>104.4</inzidenz>
        <genesen>13100</genesen>
    </day_data>
<day_data date="2021-05-22">
        <positiv_getestet>51</positiv_getestet>
        <geschaetzt_infektioes>2000</geschaetzt_infektioes>
        <inzidenz>102.9</inzidenz>
        <genesen>13100</genesen>
    </day_data>
<day_data date="2021-05-21">
        <positiv_getestet>64</positiv_getestet>
        <geschaetzt_infektioes>2000</geschaetzt_infektioes>
        <inzidenz>109.8</inzidenz>
        <genesen>13000</genesen>
    </day_data>
<day_data date="2021-05-20">
        <positiv_getestet>60</positiv_getestet>
        <geschaetzt_infektioes>2100</geschaetzt_infektioes>
        <inzidenz>100.2</inzidenz>
        <genesen>12900</genesen>
    </day_data>
<day_data date="2021-05-19">
        <positiv_getestet>108</positiv_getestet>
        <geschaetzt_infektioes>2200</geschaetzt_infektioes>
        <inzidenz>114.6</inzidenz>
        <genesen>12700</genesen>
    </day_data>
<day_data date="2021-05-18">
        <positiv_getestet>32</positiv_getestet>
        <geschaetzt_infektioes>2200</geschaetzt_infektioes>
        <inzidenz>120.3</inzidenz>
        <genesen>12600</genesen>
    </day_data>
<day_data date="2021-05-17">
        <positiv_getestet>28</positiv_getestet>
        <geschaetzt_infektioes>2300</geschaetzt_infektioes>
        <inzidenz>125.1</inzidenz>
        <genesen>12400</genesen>
    </day_data>
<day_data date="2021-05-16">
        <positiv_getestet>79</positiv_getestet>
        <geschaetzt_infektioes>2400</geschaetzt_infektioes>
        <inzidenz>119.7</inzidenz>
        <genesen>12300</genesen>
    </day_data>
<day_data date="2021-05-15">
        <positiv_getestet>33</positiv_getestet>
        <geschaetzt_infektioes>2300</geschaetzt_infektioes>
        <inzidenz>107.4</inzidenz>
        <genesen>12300</genesen>
    </day_data>
<day_data date="2021-05-14">
        <positiv_getestet>70</positiv_getestet>
        <geschaetzt_infektioes>2400</geschaetzt_infektioes>
        <inzidenz>135.8</inzidenz>
        <genesen>12200</genesen>
    </day_data>
